# Build stage
FROM node:20-alpine AS builder
RUN apk update
RUN apk add git
WORKDIR /app
RUN git clone https://github.com/jankiz/nodejs-sample-app-for-devops.git
WORKDIR /app/nodejs-sample-app-for-devops
RUN git checkout feature/monitoring
RUN npm ci
RUN npm run build

# Production stage
FROM node:20-alpine
RUN npm install -g pm2
RUN apk add curl

# Install Zabbix Agent
RUN apk add --no-cache \
    pcre \
    zabbix-agent2
# Configure Zabbix Agent
COPY zabbix_agent2.conf /etc/zabbix/zabbix_agent2.conf

# Install rsyslog
RUN apk add --no-cache rsyslog
# Create rsyslog config
COPY rsyslog.conf /etc/rsyslog.conf

RUN mkdir -p /var/log/pm2

# Configure PM2 to use syslog
ENV PM2_SYSLOG=true

WORKDIR /app
COPY --from=builder /app/nodejs-sample-app-for-devops/dist ./dist
COPY --from=builder /app/nodejs-sample-app-for-devops/package*.json ./
COPY --from=builder /app/nodejs-sample-app-for-devops/start.sh ./
RUN npm ci --only=production && npm cache clean --force
EXPOSE 3000 10050

RUN chmod +x start.sh

CMD ["./start.sh"]