apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: devops
        image: davszaa/devops:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
