apiVersion: v1
kind: Service
metadata:
  name: devops-service
spec:
  selector: 
    app: devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007
  type: NodePort
