name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  write-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Write secret into a file
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig

      - name:  Apply kubectl
        run: |
          kubectl --kubeconfig kubeconfig apply -f k8s/deployment.yaml
          kubectl --kubeconfig kubeconfig apply -f k8s/service.yaml

      - name: Delete secret
        run: |
          rm kubeconfig
