name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  write-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Write secret into a file
        run: |
          kubectl config set-cluster minikube --server=https://192.168.49.2:8443 --certificate-authority=${{ secrets.CA_CRT }} --embed-certs=true
          kubectl config set-credentials minikube --client-certificate=${{ secrets.CA_CRT }} --client-key=${{ secrets.CA_KEY }} --embed-certs=true
          kubectl config set-context minikube --cluster=minikube --user=minikube
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig

      - name:  Apply kubectl
        run: |
          kubectl --kubeconfig kubeconfig apply -f k8s/deployment.yaml
          kubectl --kubeconfig kubeconfig apply -f k8s/service.yaml

      - name: Delete secret
        run: |
          rm kubeconfig
