name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  write-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Write secret into a file
        run: |
          echo "${{ secrets.CA_CRT }}" > crt
          echo "${{ secrets.CA_KEY }}" > key
          kubectl config set-cluster minikube --server=https://192.168.49.2:8443 --certificate-authority=crt --embed-certs=true
          kubectl config set-credentials minikube --client-certificate=crt --client-key=key --embed-certs=true
          kubectl config set-context minikube --cluster=minikube --user=minikube

      - name:  Apply kubectl
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Delete secret
        run: |
          rm crt
          rm key
